//import { Inter } from "next/font/google";
import "./globals.css";
import "./fonts.css";
import "./scss/langoorai.scss"

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Langoor AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  );
}




